# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='drawed',
            field=models.BooleanField(default=False),
        ),
    ]
