# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_member', '0002_auto_20161027_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
    ]
